### ISSUE TITLE
difference in bounty display on hover

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/unitaryHACK2024#21]
On the `/bounties` page, issues are displayed differently depending on their state (open/closed). This provides a great indicator for hackers to figure out what they want to work on.

When hovering on an open issue, nothing changes, but when hovering a closed issue it's darkened (which is good for a11y) and underlined. Here's an example where the last issue is hovered.
<img width="610" alt="Screenshot 2024-06-03 at 10 09 07 AM" src="https://github.com/unitaryfund/unitaryHACK2024/assets/12703123/037d2f2a-745a-42aa-8a90-51abb67f986f">

Should we consider something similar for open issues?

@francespoblete feel free to close if you think no action is needed, or close with a commit. Happy for you to decide what's best here :)

**Comment by francespoblete** [comment]
Solved with commit 877004
https://github.com/unitaryfund/unitaryHACK2024/commit/877004eea52845735700c30b213a797a84ad5522
